version: '3.8'
services:
  app:
    build: .
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: rootpassword
      - MYSQL_DATABASE: sqldatabase
      - MYSQL_USER: user
      - MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./simple_todo.sql:/docker-entrypoint-initdb.d/simple_todo.sql
volumes:
  db_data
